# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(default='user', max_length=10),
            preserve_default=False,
        ),
    ]
