# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logId', models.CharField(max_length=5)),
                ('logTime', models.DateTimeField()),
                ('logStatus', models.CharField(max_length=50)),
                ('realName', models.CharField(max_length=20)),
                ('logContent', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
