# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_logid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='logGeneral',
            field=models.CharField(default='success', max_length=10),
            preserve_default=False,
        ),
    ]
